### ISSUE TITLE
Fix Contact form display for Safari

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/scriptchart#111]
The form appears heavily truncated, though it's possible (barely) to use it by scrolling a lot and using the tiny vertical window that's available.

It looks fine in other browsers.

**Comment by csbailey5t** [comment]
The fix here works in Safari, but screws up other static pages: https://stackoverflow.com/questions/33636796/chrome-safari-not-filling-100-height-of-flex-parent

I'm working on fixing it with some div differentiation.
