### ISSUE TITLE
Add a site-wide footer

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/scriptchart#71]
Something like the thin footer on the Chinese Deathscape site would be great: https://chinesedeathscape.supdigital.org/
Ideally it would integrate with the improved scrolling behavior of the menu and chart: https://github.com/sul-cidr/scriptchart/issues/69.

Probably a "Contact" link could go in the footer -- see also https://github.com/sul-cidr/scriptchart/issues/67.

**Comment by csbailey5t** [comment]
Effectively done in #80 and #77
